--- 
title: "Quantitative Methods and Statistics"
author:
  name: Hugo Quené \& Huub van den Bergh
  affiliation: Utrecht University
  email: h.quene@uu.nl
date: "Version compiled `r format(Sys.time(), '%d %b %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, hhmhto.bib, pandoc.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/QMS-EN
description: "Textbook on Quantitative Methods and Statistics, used a.o. in undergraduate course Methods and Statistics 1 (TL2V17002), BA Linguistics, Utrecht University, the Netherlands."
---

# Preface {-}

Data are becoming ever more important, in all parts of society, including academia, and including the humanities. The availability of large amounts of digital data (such as text, speech, video, behavioural measurements) raises new research questions, which are typically and often investigated using quantitative methods. 
Aimed at humanities researchers and students, this book offers an overview of and introduction into the most important quantitative methods and statistical techniques used in the humanities. The book provides a solid methodological foundation for quantitative research, and it introduces the most commonly used statistical techniques to describe data and to test hypotheses. This will also enable the reader to critically evaluate such quantitative research. 

This textbook is being used in the course  *Methods and Statistics 1* at Utrecht University (Linguistics program). The book is also highly suitable for self-study at a basic level, for everybody who wishes to learn more about quantitative methods and statistics. 

The main text has been kept free of mathematical derivations and formulas, which are typically not very helpful for humanities scholars and students. Our explanation is rather conceptual, and rich in examples. Where necessary we present derivations and formulas in separate sections. 

This book also contains instructions on how to "do" the statistical analyses and visualisations, using the three statistical packages SPSS, JASP, and R. These packages are further introduced in §\@ref(sec:intro-outline). These instructions too are in separate sections. 

We would like to thank our co-teachers in various courses for the many discussions and examples that have been used in any shape or form in this textbook. We thank our students for their curiosity and for their sharp eyes in spotting errors and inconsistencies in previous versions. 

We are also thankful to 
Gerrit Bloothooft, 
Margot van den Berg, 
Willemijn Heeren, 
Rianne Kraakman, 
Caspar van Lissa,
Els Rose, 
Tobias Quené, 
Kirsten Schutter,
Marijn Struiksma, 
Tara Super, 
and Joanna Wall, 
for their advice, data, comments and suggestions. 

We thank Rianne Kraakman for writing the subsections on JASP instructions (version 1.2.0), Aleksei Nazarov and Joanna Wall for translating this book from Dutch to English (version 1.2.0), and Tara Super for editing (version 1.3.0). 

Special thanks are due to Marijn Struiksma, for inspiration and for coordinating the JASP additions and the English translation. 

February 2021 (version 1.1.1)\
June 2021 (version 1.2.0)\
May 2022 (version 1.3.0)

Hugo Quené, <https://www.hugoquene.nl>

Huub van den Bergh, <https://www.uu.nl/staff/HHvandenBergh>

---

## Liever Nederlands? {-}

This is the English version of the textbook, titled *Quantitative Methods and Statistics*.

U leest nu de Engelstalige versie van het tekstboek. Er is ook een parallelle Nederlandstalige versie, getiteld *Kwantitatieve Methoden en Statistiek*, te vinden via <https://hugoquene.github.io/KMS-NL/>. 


## Notation {-}

Following international usage we use the full stop (decimal point) as decimal separator; hence we write $\frac{3}{2}=1.5$. Note that the decimal separator may vary between computers and between software packages on the same computer. Check which decimal separator is used by (each software package on) your computer. 

## License {-}

This document is licensed under the _GNU GPL 3_ license (for details see 
https://www.gnu.org/licenses/gpl-3.0.en.html). 

## Citation {-}

Please cite this work as follows (in APA style, and substitute the date):

Quené, H. \& Van den Bergh, H. (2022). *Quantitative Methods and Statistics*. 
Retrieved 13 May 2022 from <https://hugoquene.github.io/QMS-EN/> .

## Technical details {-}

All materials for this textbook are availabe at 
<https://doi.org/10.5281/zenodo.4479620> or directly from 
<https://github.com/hugoquene/QMS-EN>: 
this includes other versions of this textbook (EPUB, PDF, HTML), the source code (Rmarkdown and R) of the text including figures and examples, accompanying datasets used in the text, and figures as separate files.

The original Dutch version of this text was written in LaTeX, and was then converted to Rmarkdown, using `pandoc` [@pandoc] and the `bookdown` package [@R-bookdown] in [Rstudio](https://www.rstudio.com). The parallel Dutch version is available at <https://hugoquene.github.io/KMS-NL>.
The English translation is based on the Dutch LaTeX version (for Part I) and Rmarkdown version (for Parts II and III).


## About the authors {-}

Both authors work at the Faculty of Humanities at Utrecht University, the Netherlands.
HQ is professor in the Quantitative Methods of Empirical Research in the Humanities, and he is also founding director of the Centre for Digital Humanities at Utrecht University. HvdB is professor in the Pedagogy and Testing of Language Proficiency, and he is also section chair in Dutch Language and Literature at the Dutch National Board of Tests and Examinations (CvTE).

```{r include=FALSE}
# automatically create a bib database for R packages
require(lattice)
require(nnet)
# added 20220203
require(hqmisc)
# require(MASS)
knitr::write_bib( c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
