<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11 Correlation and regression | Quantitative Methods and Statistics</title>
  <meta name="description" content="Textbook on Quantitative Methods and Statistics, used a.o. in undergraduate course Methods and Statistics 1 (TL2V17002), BA Linguistics, Utrecht University, the Netherlands." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="11 Correlation and regression | Quantitative Methods and Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Textbook on Quantitative Methods and Statistics, used a.o. in undergraduate course Methods and Statistics 1 (TL2V17002), BA Linguistics, Utrecht University, the Netherlands." />
  <meta name="github-repo" content="rstudio/QMS-EN" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11 Correlation and regression | Quantitative Methods and Statistics" />
  
  <meta name="twitter:description" content="Textbook on Quantitative Methods and Statistics, used a.o. in undergraduate course Methods and Statistics 1 (TL2V17002), BA Linguistics, Utrecht University, the Netherlands." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch-probability-distributions.html"/>
<link rel="next" href="ch-reliability.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Quantitative Methods and Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#liever-nederlands"><i class="fa fa-check"></i>Liever Nederlands?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notation"><i class="fa fa-check"></i>Notation</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citation"><i class="fa fa-check"></i>Citation</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#technical-details"><i class="fa fa-check"></i>Technical details</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-authors"><i class="fa fa-check"></i>About the authors</a></li>
</ul></li>
<li class="part"><span><b>Part I: Methodology</b></span></li>
<li class="chapter" data-level="1" data-path="ch-introduction.html"><a href="ch-introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:scientific-research"><i class="fa fa-check"></i><b>1.1</b> Scientific research</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:theory"><i class="fa fa-check"></i><b>1.1.1</b> Theory</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:paradigms"><i class="fa fa-check"></i><b>1.2</b> Paradigms</a></li>
<li class="chapter" data-level="1.3" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:instrument-validation"><i class="fa fa-check"></i><b>1.3</b> Instrument validation</a></li>
<li class="chapter" data-level="1.4" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:descriptive-research"><i class="fa fa-check"></i><b>1.4</b> Descriptive research</a></li>
<li class="chapter" data-level="1.5" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:experimental-research"><i class="fa fa-check"></i><b>1.5</b> Experimental research</a></li>
<li class="chapter" data-level="1.6" data-path="ch-introduction.html"><a href="ch-introduction.html#sec:intro-outline"><i class="fa fa-check"></i><b>1.6</b> Outline of this textbook</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch-research.html"><a href="ch-research.html"><i class="fa fa-check"></i><b>2</b> Hypothesis testing research</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ch-research.html"><a href="ch-research.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="ch-research.html"><a href="ch-research.html#sec:variables"><i class="fa fa-check"></i><b>2.2</b> Variables</a></li>
<li class="chapter" data-level="2.3" data-path="ch-research.html"><a href="ch-research.html#sec:independendependentvariables"><i class="fa fa-check"></i><b>2.3</b> Independent and dependent variables</a></li>
<li class="chapter" data-level="2.4" data-path="ch-research.html"><a href="ch-research.html#sec:falsification"><i class="fa fa-check"></i><b>2.4</b> Falsification and null hypothesis</a></li>
<li class="chapter" data-level="2.5" data-path="ch-research.html"><a href="ch-research.html#sec:empiricalcycle"><i class="fa fa-check"></i><b>2.5</b> The empirical cycle</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="ch-research.html"><a href="ch-research.html#observation"><i class="fa fa-check"></i><b>2.5.1</b> observation</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch-research.html"><a href="ch-research.html#induction"><i class="fa fa-check"></i><b>2.5.2</b> induction</a></li>
<li class="chapter" data-level="2.5.3" data-path="ch-research.html"><a href="ch-research.html#deduction"><i class="fa fa-check"></i><b>2.5.3</b> deduction</a></li>
<li class="chapter" data-level="2.5.4" data-path="ch-research.html"><a href="ch-research.html#testing"><i class="fa fa-check"></i><b>2.5.4</b> testing</a></li>
<li class="chapter" data-level="2.5.5" data-path="ch-research.html"><a href="ch-research.html#evaluation"><i class="fa fa-check"></i><b>2.5.5</b> evaluation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch-research.html"><a href="ch-research.html#sec:makingchoices"><i class="fa fa-check"></i><b>2.6</b> Making choices</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch-integrity.html"><a href="ch-integrity.html"><i class="fa fa-check"></i><b>3</b> Integrity</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ch-integrity.html"><a href="ch-integrity.html#sec:integrity-introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="ch-integrity.html"><a href="ch-integrity.html#sec:design"><i class="fa fa-check"></i><b>3.2</b> Design</a></li>
<li class="chapter" data-level="3.3" data-path="ch-integrity.html"><a href="ch-integrity.html#participants-and-informants"><i class="fa fa-check"></i><b>3.3</b> Participants and informants</a></li>
<li class="chapter" data-level="3.4" data-path="ch-integrity.html"><a href="ch-integrity.html#data"><i class="fa fa-check"></i><b>3.4</b> Data</a></li>
<li class="chapter" data-level="3.5" data-path="ch-integrity.html"><a href="ch-integrity.html#writing"><i class="fa fa-check"></i><b>3.5</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html"><i class="fa fa-check"></i><b>4</b> Levels of measurement</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#sec:nominal"><i class="fa fa-check"></i><b>4.2</b> Nominal</a></li>
<li class="chapter" data-level="4.3" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#sec:ordinal"><i class="fa fa-check"></i><b>4.3</b> Ordinal</a></li>
<li class="chapter" data-level="4.4" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#sec:interval"><i class="fa fa-check"></i><b>4.4</b> Interval</a></li>
<li class="chapter" data-level="4.5" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#sec:ratio"><i class="fa fa-check"></i><b>4.5</b> Ratio</a></li>
<li class="chapter" data-level="4.6" data-path="ch-levelsofmeasurement.html"><a href="ch-levelsofmeasurement.html#sec:orderinglevelsofmeasurement"><i class="fa fa-check"></i><b>4.6</b> Ordering of levels of measurement</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch-validity.html"><a href="ch-validity.html"><i class="fa fa-check"></i><b>5</b> Validity</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ch-validity.html"><a href="ch-validity.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="ch-validity.html"><a href="ch-validity.html#sec:causality"><i class="fa fa-check"></i><b>5.2</b> Causality</a></li>
<li class="chapter" data-level="5.3" data-path="ch-validity.html"><a href="ch-validity.html#sec:validity"><i class="fa fa-check"></i><b>5.3</b> Validity</a></li>
<li class="chapter" data-level="5.4" data-path="ch-validity.html"><a href="ch-validity.html#sec:internalvalidity"><i class="fa fa-check"></i><b>5.4</b> Internal validity</a></li>
<li class="chapter" data-level="5.5" data-path="ch-validity.html"><a href="ch-validity.html#sec:constructvalidity"><i class="fa fa-check"></i><b>5.5</b> Construct validity</a></li>
<li class="chapter" data-level="5.6" data-path="ch-validity.html"><a href="ch-validity.html#sec:externalvalidity"><i class="fa fa-check"></i><b>5.6</b> External validity</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch-design.html"><a href="ch-design.html"><i class="fa fa-check"></i><b>6</b> Design</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ch-design.html"><a href="ch-design.html#sec:design-introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="ch-design.html"><a href="ch-design.html#sec:betweenwithinparticipants"><i class="fa fa-check"></i><b>6.2</b> Between or within ?</a></li>
<li class="chapter" data-level="6.3" data-path="ch-design.html"><a href="ch-design.html#sec:one-shot-single-case-design"><i class="fa fa-check"></i><b>6.3</b> The one-shot single-case design</a></li>
<li class="chapter" data-level="6.4" data-path="ch-design.html"><a href="ch-design.html#sec:one-group-pretest-posttest-design"><i class="fa fa-check"></i><b>6.4</b> The one-group pretest-posttest design</a></li>
<li class="chapter" data-level="6.5" data-path="ch-design.html"><a href="ch-design.html#sec:pretest-posttest-control-group-design"><i class="fa fa-check"></i><b>6.5</b> The pretest-posttest-control group design</a></li>
<li class="chapter" data-level="6.6" data-path="ch-design.html"><a href="ch-design.html#sec:solomon-four-groups-design"><i class="fa fa-check"></i><b>6.6</b> The Solomon-four-groups design</a></li>
<li class="chapter" data-level="6.7" data-path="ch-design.html"><a href="ch-design.html#the-posttest-only-control-group-design"><i class="fa fa-check"></i><b>6.7</b> The posttest-only control group design</a></li>
<li class="chapter" data-level="6.8" data-path="ch-design.html"><a href="ch-design.html#sec:factorial-designs"><i class="fa fa-check"></i><b>6.8</b> Factorial designs</a></li>
<li class="chapter" data-level="6.9" data-path="ch-design.html"><a href="ch-design.html#sec:within-subject-designs"><i class="fa fa-check"></i><b>6.9</b> Within-subject designs</a></li>
<li class="chapter" data-level="6.10" data-path="ch-design.html"><a href="ch-design.html#designing-a-study"><i class="fa fa-check"></i><b>6.10</b> Designing a study</a></li>
<li class="chapter" data-level="6.11" data-path="ch-design.html"><a href="ch-design.html#in-conclusion"><i class="fa fa-check"></i><b>6.11</b> In conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch-samples.html"><a href="ch-samples.html"><i class="fa fa-check"></i><b>7</b> Samples</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ch-samples.html"><a href="ch-samples.html#sec:convenience-samples"><i class="fa fa-check"></i><b>7.1</b> Convenience samples</a></li>
<li class="chapter" data-level="7.2" data-path="ch-samples.html"><a href="ch-samples.html#sec:systematic-samples"><i class="fa fa-check"></i><b>7.2</b> Systematic samples</a></li>
<li class="chapter" data-level="7.3" data-path="ch-samples.html"><a href="ch-samples.html#sec:random-samples"><i class="fa fa-check"></i><b>7.3</b> Random samples</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ch-samples.html"><a href="ch-samples.html#spss"><i class="fa fa-check"></i><b>7.3.1</b> SPSS</a></li>
<li class="chapter" data-level="7.3.2" data-path="ch-samples.html"><a href="ch-samples.html#jasp"><i class="fa fa-check"></i><b>7.3.2</b> JASP</a></li>
<li class="chapter" data-level="7.3.3" data-path="ch-samples.html"><a href="ch-samples.html#r"><i class="fa fa-check"></i><b>7.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ch-samples.html"><a href="ch-samples.html#sec:sample-size"><i class="fa fa-check"></i><b>7.4</b> Sample size</a></li>
</ul></li>
<li class="part"><span><b>Part II: Descriptive statistics</b></span></li>
<li class="chapter" data-level="8" data-path="ch-frequencies.html"><a href="ch-frequencies.html"><i class="fa fa-check"></i><b>8</b> Frequencies</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ch-frequencies.html"><a href="ch-frequencies.html#introduction-3"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="ch-frequencies.html"><a href="ch-frequencies.html#sec:frequencies"><i class="fa fa-check"></i><b>8.2</b> Frequencies</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ch-frequencies.html"><a href="ch-frequencies.html#sec:intervals"><i class="fa fa-check"></i><b>8.2.1</b> Intervals</a></li>
<li class="chapter" data-level="8.2.2" data-path="ch-frequencies.html"><a href="ch-frequencies.html#spss-1"><i class="fa fa-check"></i><b>8.2.2</b> SPSS</a></li>
<li class="chapter" data-level="8.2.3" data-path="ch-frequencies.html"><a href="ch-frequencies.html#jasp-1"><i class="fa fa-check"></i><b>8.2.3</b> JASP</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ch-frequencies.html"><a href="ch-frequencies.html#sec:barcharts"><i class="fa fa-check"></i><b>8.3</b> Bar charts</a></li>
<li class="chapter" data-level="8.4" data-path="ch-frequencies.html"><a href="ch-frequencies.html#sec:histograms"><i class="fa fa-check"></i><b>8.4</b> Histograms</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ch-frequencies.html"><a href="ch-frequencies.html#spss-2"><i class="fa fa-check"></i><b>8.4.1</b> SPSS</a></li>
<li class="chapter" data-level="8.4.2" data-path="ch-frequencies.html"><a href="ch-frequencies.html#jasp-2"><i class="fa fa-check"></i><b>8.4.2</b> JASP</a></li>
<li class="chapter" data-level="8.4.3" data-path="ch-frequencies.html"><a href="ch-frequencies.html#r-1"><i class="fa fa-check"></i><b>8.4.3</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html"><i class="fa fa-check"></i><b>9</b> Centre and dispersion</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#introduction-4"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#symbols"><i class="fa fa-check"></i><b>9.2</b> Symbols</a></li>
<li class="chapter" data-level="9.3" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#central-tendencies"><i class="fa fa-check"></i><b>9.3</b> Central tendencies</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:mean"><i class="fa fa-check"></i><b>9.3.1</b> mean</a></li>
<li class="chapter" data-level="9.3.2" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:median"><i class="fa fa-check"></i><b>9.3.2</b> median</a></li>
<li class="chapter" data-level="9.3.3" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#mode"><i class="fa fa-check"></i><b>9.3.3</b> mode</a></li>
<li class="chapter" data-level="9.3.4" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:harmonicmean"><i class="fa fa-check"></i><b>9.3.4</b> Harmonic mean</a></li>
<li class="chapter" data-level="9.3.5" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#winsorized-mean"><i class="fa fa-check"></i><b>9.3.5</b> winsorized mean</a></li>
<li class="chapter" data-level="9.3.6" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#trimmed-mean"><i class="fa fa-check"></i><b>9.3.6</b> trimmed mean</a></li>
<li class="chapter" data-level="9.3.7" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#comparison-of-central-tendencies"><i class="fa fa-check"></i><b>9.3.7</b> comparison of central tendencies</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:quartiles-and-boxplots"><i class="fa fa-check"></i><b>9.4</b> Quartiles and boxplots</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#quartiles"><i class="fa fa-check"></i><b>9.4.1</b> Quartiles</a></li>
<li class="chapter" data-level="9.4.2" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:outliers"><i class="fa fa-check"></i><b>9.4.2</b> Outliers</a></li>
<li class="chapter" data-level="9.4.3" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:boxplot"><i class="fa fa-check"></i><b>9.4.3</b> Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:measures-of-dispersion"><i class="fa fa-check"></i><b>9.5</b> Measures of dispersion</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:variance"><i class="fa fa-check"></i><b>9.5.1</b> Variance</a></li>
<li class="chapter" data-level="9.5.2" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:standarddeviation"><i class="fa fa-check"></i><b>9.5.2</b> standard deviation</a></li>
<li class="chapter" data-level="9.5.3" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#mad"><i class="fa fa-check"></i><b>9.5.3</b> MAD</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:significantfigures"><i class="fa fa-check"></i><b>9.6</b> On significant figures</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:significantfigures-means"><i class="fa fa-check"></i><b>9.6.1</b> Mean and standard deviation</a></li>
<li class="chapter" data-level="9.6.2" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#percentages"><i class="fa fa-check"></i><b>9.6.2</b> Percentages</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:robustefficient"><i class="fa fa-check"></i><b>9.7</b> Making choices</a></li>
<li class="chapter" data-level="9.8" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#sec:standardscores"><i class="fa fa-check"></i><b>9.8</b> Standard scores</a></li>
<li class="chapter" data-level="9.9" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#spss-3"><i class="fa fa-check"></i><b>9.9</b> SPSS</a></li>
<li class="chapter" data-level="9.10" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#jasp-3"><i class="fa fa-check"></i><b>9.10</b> JASP</a></li>
<li class="chapter" data-level="9.11" data-path="ch-centre-and-dispersion.html"><a href="ch-centre-and-dispersion.html#r-2"><i class="fa fa-check"></i><b>9.11</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html"><i class="fa fa-check"></i><b>10</b> Probability distributions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:probabilities"><i class="fa fa-check"></i><b>10.1</b> Probabilities</a></li>
<li class="chapter" data-level="10.2" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:binomial-distribution"><i class="fa fa-check"></i><b>10.2</b> Binomial probability distribution</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#formulas"><i class="fa fa-check"></i><b>10.2.1</b> formulas</a></li>
<li class="chapter" data-level="10.2.2" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#jasp-4"><i class="fa fa-check"></i><b>10.2.2</b> JASP</a></li>
<li class="chapter" data-level="10.2.3" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#r-3"><i class="fa fa-check"></i><b>10.2.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:normaldistribution"><i class="fa fa-check"></i><b>10.3</b> Normal probability distribution</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#formulas-1"><i class="fa fa-check"></i><b>10.3.1</b> formulas</a></li>
<li class="chapter" data-level="10.3.2" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#jasp-5"><i class="fa fa-check"></i><b>10.3.2</b> JASP</a></li>
<li class="chapter" data-level="10.3.3" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#r-4"><i class="fa fa-check"></i><b>10.3.3</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:isvarnormaldistributed"><i class="fa fa-check"></i><b>10.4</b> Does my variable have a normal probability distribution?</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#spss-4"><i class="fa fa-check"></i><b>10.4.1</b> SPSS</a></li>
<li class="chapter" data-level="10.4.2" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#r-5"><i class="fa fa-check"></i><b>10.4.2</b> R</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:whatifnotnormal"><i class="fa fa-check"></i><b>10.5</b> What if my variable is not normally distributed?</a></li>
<li class="chapter" data-level="10.6" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:Centrallimittheorem"><i class="fa fa-check"></i><b>10.6</b> Probability distribution of average</a></li>
<li class="chapter" data-level="10.7" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#sec:confidenceinterval-mean"><i class="fa fa-check"></i><b>10.7</b> Confidence interval of the mean</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="ch-probability-distributions.html"><a href="ch-probability-distributions.html#formulas-2"><i class="fa fa-check"></i><b>10.7.1</b> formulas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html"><i class="fa fa-check"></i><b>11</b> Correlation and regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#introduction-5"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:Pearson"><i class="fa fa-check"></i><b>11.2</b> Pearson product-moment correlation</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#formulas-3"><i class="fa fa-check"></i><b>11.2.1</b> Formulas</a></li>
<li class="chapter" data-level="11.2.2" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#spss-5"><i class="fa fa-check"></i><b>11.2.2</b> SPSS</a></li>
<li class="chapter" data-level="11.2.3" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#jasp-6"><i class="fa fa-check"></i><b>11.2.3</b> JASP</a></li>
<li class="chapter" data-level="11.2.4" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#r-6"><i class="fa fa-check"></i><b>11.2.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:regression"><i class="fa fa-check"></i><b>11.3</b> Regression</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:regression-formulas"><i class="fa fa-check"></i><b>11.3.1</b> Formulas</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#spss-6"><i class="fa fa-check"></i><b>11.3.2</b> SPSS</a></li>
<li class="chapter" data-level="11.3.3" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#jasp-7"><i class="fa fa-check"></i><b>11.3.3</b> JASP</a></li>
<li class="chapter" data-level="11.3.4" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#r-7"><i class="fa fa-check"></i><b>11.3.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#influential-observations"><i class="fa fa-check"></i><b>11.4</b> Influential observations</a></li>
<li class="chapter" data-level="11.5" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:Spearman"><i class="fa fa-check"></i><b>11.5</b> Spearman’s rank correlation coefficient</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#formulas-4"><i class="fa fa-check"></i><b>11.5.1</b> Formulas</a></li>
<li class="chapter" data-level="11.5.2" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#spss-7"><i class="fa fa-check"></i><b>11.5.2</b> SPSS</a></li>
<li class="chapter" data-level="11.5.3" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#jasp-8"><i class="fa fa-check"></i><b>11.5.3</b> JASP</a></li>
<li class="chapter" data-level="11.5.4" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#r-8"><i class="fa fa-check"></i><b>11.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:Phi"><i class="fa fa-check"></i><b>11.6</b> Phi</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#formulas-5"><i class="fa fa-check"></i><b>11.6.1</b> Formulas</a></li>
<li class="chapter" data-level="11.6.2" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#spss-8"><i class="fa fa-check"></i><b>11.6.2</b> SPSS</a></li>
<li class="chapter" data-level="11.6.3" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#jasp-9"><i class="fa fa-check"></i><b>11.6.3</b> JASP</a></li>
<li class="chapter" data-level="11.6.4" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#r-9"><i class="fa fa-check"></i><b>11.6.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="ch-correlation-regression.html"><a href="ch-correlation-regression.html#sec:correlationcausation"><i class="fa fa-check"></i><b>11.7</b> Last but not least</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ch-reliability.html"><a href="ch-reliability.html"><i class="fa fa-check"></i><b>12</b> Reliability</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ch-reliability.html"><a href="ch-reliability.html#introduction-6"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="ch-reliability.html"><a href="ch-reliability.html#what-is-reliability"><i class="fa fa-check"></i><b>12.2</b> What is reliability?</a></li>
<li class="chapter" data-level="12.3" data-path="ch-reliability.html"><a href="ch-reliability.html#test-theory"><i class="fa fa-check"></i><b>12.3</b> Test theory</a></li>
<li class="chapter" data-level="12.4" data-path="ch-reliability.html"><a href="ch-reliability.html#interpretations"><i class="fa fa-check"></i><b>12.4</b> Interpretations</a></li>
<li class="chapter" data-level="12.5" data-path="ch-reliability.html"><a href="ch-reliability.html#methods-for-estimating-reliability"><i class="fa fa-check"></i><b>12.5</b> Methods for estimating reliability</a></li>
<li class="chapter" data-level="12.6" data-path="ch-reliability.html"><a href="ch-reliability.html#reliability-between-assessors"><i class="fa fa-check"></i><b>12.6</b> Reliability between assessors</a></li>
<li class="chapter" data-level="12.7" data-path="ch-reliability.html"><a href="ch-reliability.html#reliability-and-construct-validity"><i class="fa fa-check"></i><b>12.7</b> Reliability and construct validity</a></li>
<li class="chapter" data-level="12.8" data-path="ch-reliability.html"><a href="ch-reliability.html#spss-9"><i class="fa fa-check"></i><b>12.8</b> SPSS</a></li>
<li class="chapter" data-level="12.9" data-path="ch-reliability.html"><a href="ch-reliability.html#jasp-10"><i class="fa fa-check"></i><b>12.9</b> JASP</a></li>
<li class="chapter" data-level="12.10" data-path="ch-reliability.html"><a href="ch-reliability.html#r-10"><i class="fa fa-check"></i><b>12.10</b> R</a></li>
</ul></li>
<li class="part"><span><b>Part III: Inferential statistics</b></span></li>
<li class="chapter" data-level="13" data-path="ch-testing.html"><a href="ch-testing.html"><i class="fa fa-check"></i><b>13</b> Testing hypotheses</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ch-testing.html"><a href="ch-testing.html#sec:testing-introduction"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-onesample"><i class="fa fa-check"></i><b>13.2</b> One-sample <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-freedomdegrees"><i class="fa fa-check"></i><b>13.2.1</b> Degrees of freedom</a></li>
<li class="chapter" data-level="13.2.2" data-path="ch-testing.html"><a href="ch-testing.html#sec:formulas13-1"><i class="fa fa-check"></i><b>13.2.2</b> formulas</a></li>
<li class="chapter" data-level="13.2.3" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-assumptions"><i class="fa fa-check"></i><b>13.2.3</b> assumptions</a></li>
<li class="chapter" data-level="13.2.4" data-path="ch-testing.html"><a href="ch-testing.html#spss-10"><i class="fa fa-check"></i><b>13.2.4</b> SPSS</a></li>
<li class="chapter" data-level="13.2.5" data-path="ch-testing.html"><a href="ch-testing.html#sec:jaspttestonesample"><i class="fa fa-check"></i><b>13.2.5</b> JASP</a></li>
<li class="chapter" data-level="13.2.6" data-path="ch-testing.html"><a href="ch-testing.html#r-11"><i class="fa fa-check"></i><b>13.2.6</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ch-testing.html"><a href="ch-testing.html#sec:plargerthannull"><i class="fa fa-check"></i><b>13.3</b> <span class="math inline">\(p\)</span>-value is always larger than zero</a></li>
<li class="chapter" data-level="13.4" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-onesidedtwosided"><i class="fa fa-check"></i><b>13.4</b> One-sided and two-sided tests</a></li>
<li class="chapter" data-level="13.5" data-path="ch-testing.html"><a href="ch-testing.html#sec:t-confidenceinterval-mean"><i class="fa fa-check"></i><b>13.5</b> Confidence interval of the mean</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="ch-testing.html"><a href="ch-testing.html#sec:formulas13-2"><i class="fa fa-check"></i><b>13.5.1</b> formulas</a></li>
<li class="chapter" data-level="13.5.2" data-path="ch-testing.html"><a href="ch-testing.html#spss-11"><i class="fa fa-check"></i><b>13.5.2</b> SPSS</a></li>
<li class="chapter" data-level="13.5.3" data-path="ch-testing.html"><a href="ch-testing.html#jasp-11"><i class="fa fa-check"></i><b>13.5.3</b> JASP</a></li>
<li class="chapter" data-level="13.5.4" data-path="ch-testing.html"><a href="ch-testing.html#r-12"><i class="fa fa-check"></i><b>13.5.4</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-indep"><i class="fa fa-check"></i><b>13.6</b> Independent samples <span class="math inline">\(t\)</span>-tests</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-unpaired-assumptions"><i class="fa fa-check"></i><b>13.6.1</b> assumptions</a></li>
<li class="chapter" data-level="13.6.2" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-formulas"><i class="fa fa-check"></i><b>13.6.2</b> formulas</a></li>
<li class="chapter" data-level="13.6.3" data-path="ch-testing.html"><a href="ch-testing.html#sec:SPSS-ttest-unpaired"><i class="fa fa-check"></i><b>13.6.3</b> SPSS</a></li>
<li class="chapter" data-level="13.6.4" data-path="ch-testing.html"><a href="ch-testing.html#sec:JASP-ttest-unpaired"><i class="fa fa-check"></i><b>13.6.4</b> JASP</a></li>
<li class="chapter" data-level="13.6.5" data-path="ch-testing.html"><a href="ch-testing.html#sec:R-ttest-unpaired"><i class="fa fa-check"></i><b>13.6.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-paired"><i class="fa fa-check"></i><b>13.7</b> <span class="math inline">\(t\)</span>-test for paired observations</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="ch-testing.html"><a href="ch-testing.html#assumptions-1"><i class="fa fa-check"></i><b>13.7.1</b> assumptions</a></li>
<li class="chapter" data-level="13.7.2" data-path="ch-testing.html"><a href="ch-testing.html#sec:formulas13-4"><i class="fa fa-check"></i><b>13.7.2</b> formulas</a></li>
<li class="chapter" data-level="13.7.3" data-path="ch-testing.html"><a href="ch-testing.html#sec:SPSS-ttest-paired"><i class="fa fa-check"></i><b>13.7.3</b> SPSS</a></li>
<li class="chapter" data-level="13.7.4" data-path="ch-testing.html"><a href="ch-testing.html#sec:JASP-ttest-paired"><i class="fa fa-check"></i><b>13.7.4</b> JASP</a></li>
<li class="chapter" data-level="13.7.5" data-path="ch-testing.html"><a href="ch-testing.html#sec:R-ttest-paired"><i class="fa fa-check"></i><b>13.7.5</b> R</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="ch-testing.html"><a href="ch-testing.html#sec:ttest-effectsize"><i class="fa fa-check"></i><b>13.8</b> Effect size</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="ch-testing.html"><a href="ch-testing.html#sec:formulas13-5"><i class="fa fa-check"></i><b>13.8.1</b> formulas</a></li>
<li class="chapter" data-level="13.8.2" data-path="ch-testing.html"><a href="ch-testing.html#spss-13-2"><i class="fa fa-check"></i><b>13.8.2</b> SPSS</a></li>
<li class="chapter" data-level="13.8.3" data-path="ch-testing.html"><a href="ch-testing.html#jasp-12"><i class="fa fa-check"></i><b>13.8.3</b> JASP</a></li>
<li class="chapter" data-level="13.8.4" data-path="ch-testing.html"><a href="ch-testing.html#r-13"><i class="fa fa-check"></i><b>13.8.4</b> R</a></li>
<li class="chapter" data-level="13.8.5" data-path="ch-testing.html"><a href="ch-testing.html#sec:confint-effectsize"><i class="fa fa-check"></i><b>13.8.5</b> Confidence interval of the effect size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ch-power.html"><a href="ch-power.html"><i class="fa fa-check"></i><b>14</b> Power</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ch-power.html"><a href="ch-power.html#sec:power-introduction"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="ch-power.html"><a href="ch-power.html#sec:effectsize-power"><i class="fa fa-check"></i><b>14.2</b> Relation between effect size and power</a></li>
<li class="chapter" data-level="14.3" data-path="ch-power.html"><a href="ch-power.html#sec:samplesize-power"><i class="fa fa-check"></i><b>14.3</b> Relation between sample size and power</a></li>
<li class="chapter" data-level="14.4" data-path="ch-power.html"><a href="ch-power.html#sec:significancelevel-power"><i class="fa fa-check"></i><b>14.4</b> Relation between significance level and power</a></li>
<li class="chapter" data-level="14.5" data-path="ch-power.html"><a href="ch-power.html#disadvantages-of-insufficient-power"><i class="fa fa-check"></i><b>14.5</b> Disadvantages of insufficient power</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ch-anova.html"><a href="ch-anova.html"><i class="fa fa-check"></i><b>15</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ch-anova.html"><a href="ch-anova.html#sec:introduction"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-examples"><i class="fa fa-check"></i><b>15.2</b> Some examples</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="ch-anova.html"><a href="ch-anova.html#assumptions"><i class="fa fa-check"></i><b>15.2.1</b> assumptions</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="ch-anova.html"><a href="ch-anova.html#one-way-analysis-of-variance"><i class="fa fa-check"></i><b>15.3</b> One-way analysis of variance</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-oneway-explanation"><i class="fa fa-check"></i><b>15.3.1</b> An intuitive explanation</a></li>
<li class="chapter" data-level="15.3.2" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-oneway-formal"><i class="fa fa-check"></i><b>15.3.2</b> A formal explanation</a></li>
<li class="chapter" data-level="15.3.3" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-oneway-effectsize"><i class="fa fa-check"></i><b>15.3.3</b> Effect size</a></li>
<li class="chapter" data-level="15.3.4" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-oneway-planned"><i class="fa fa-check"></i><b>15.3.4</b> Planned comparisons</a></li>
<li class="chapter" data-level="15.3.5" data-path="ch-anova.html"><a href="ch-anova.html#sec:anova-oneway-posthoc"><i class="fa fa-check"></i><b>15.3.5</b> Post-hoc comparisons</a></li>
<li class="chapter" data-level="15.3.6" data-path="ch-anova.html"><a href="ch-anova.html#spss-12"><i class="fa fa-check"></i><b>15.3.6</b> SPSS</a></li>
<li class="chapter" data-level="15.3.7" data-path="ch-anova.html"><a href="ch-anova.html#jasp-13"><i class="fa fa-check"></i><b>15.3.7</b> JASP</a></li>
<li class="chapter" data-level="15.3.8" data-path="ch-anova.html"><a href="ch-anova.html#r-14"><i class="fa fa-check"></i><b>15.3.8</b> R</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="ch-anova.html"><a href="ch-anova.html#two-way-analysis-of-variance"><i class="fa fa-check"></i><b>15.4</b> Two-way analysis of variance</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="ch-anova.html"><a href="ch-anova.html#an-intuitive-explanation"><i class="fa fa-check"></i><b>15.4.1</b> An intuitive explanation</a></li>
<li class="chapter" data-level="15.4.2" data-path="ch-anova.html"><a href="ch-anova.html#a-formal-explanation"><i class="fa fa-check"></i><b>15.4.2</b> A formal explanation</a></li>
<li class="chapter" data-level="15.4.3" data-path="ch-anova.html"><a href="ch-anova.html#spss-13"><i class="fa fa-check"></i><b>15.4.3</b> SPSS</a></li>
<li class="chapter" data-level="15.4.4" data-path="ch-anova.html"><a href="ch-anova.html#jasp-14"><i class="fa fa-check"></i><b>15.4.4</b> JASP</a></li>
<li class="chapter" data-level="15.4.5" data-path="ch-anova.html"><a href="ch-anova.html#r-15"><i class="fa fa-check"></i><b>15.4.5</b> R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html"><i class="fa fa-check"></i><b>16</b> Chi-square-tests</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#sec:ch16introduction"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#sec:chi2gof"><i class="fa fa-check"></i><b>16.2</b> <span class="math inline">\(\chi^2\)</span> test for “goodness of fit” in single sample</a></li>
<li class="chapter" data-level="16.3" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#chi2-test-for-homogeneity-of-a-variable-in-multiple-samples"><i class="fa fa-check"></i><b>16.3</b> <span class="math inline">\(\chi^2\)</span> test for homogeneity of a variable in multiple samples</a></li>
<li class="chapter" data-level="16.4" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#chi2-test-for-association-between-two-variables-in-single-sample"><i class="fa fa-check"></i><b>16.4</b> <span class="math inline">\(\chi^2\)</span> test for association between two variables in single sample</a></li>
<li class="chapter" data-level="16.5" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#sec:chi2test-assumptions"><i class="fa fa-check"></i><b>16.5</b> assumptions</a></li>
<li class="chapter" data-level="16.6" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#formulas-6"><i class="fa fa-check"></i><b>16.6</b> formulas</a></li>
<li class="chapter" data-level="16.7" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#spss-14"><i class="fa fa-check"></i><b>16.7</b> SPSS</a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#goodness-of-fit-preparation"><i class="fa fa-check"></i><b>16.7.1</b> goodness of fit: preparation</a></li>
<li class="chapter" data-level="16.7.2" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#goodness-of-fit-testing"><i class="fa fa-check"></i><b>16.7.2</b> goodness of fit: testing</a></li>
<li class="chapter" data-level="16.7.3" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#contingency-tables-preparation"><i class="fa fa-check"></i><b>16.7.3</b> contingency tables: preparation</a></li>
<li class="chapter" data-level="16.7.4" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#contingency-tables-testing"><i class="fa fa-check"></i><b>16.7.4</b> contingency tables: testing</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#jasp-15"><i class="fa fa-check"></i><b>16.8</b> JASP</a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#goodness-of-fit-preparation-1"><i class="fa fa-check"></i><b>16.8.1</b> goodness of fit: preparation</a></li>
<li class="chapter" data-level="16.8.2" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#goodness-of-fit-testing-1"><i class="fa fa-check"></i><b>16.8.2</b> goodness of fit: testing</a></li>
<li class="chapter" data-level="16.8.3" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#contingency-tables-preparation-1"><i class="fa fa-check"></i><b>16.8.3</b> contingency tables: preparation</a></li>
<li class="chapter" data-level="16.8.4" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#contingency-tables-testing-1"><i class="fa fa-check"></i><b>16.8.4</b> contingency tables: testing</a></li>
</ul></li>
<li class="chapter" data-level="16.9" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#r-16"><i class="fa fa-check"></i><b>16.9</b> R</a>
<ul>
<li class="chapter" data-level="16.9.1" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#goodness-of-fit-testing-2"><i class="fa fa-check"></i><b>16.9.1</b> goodness of fit: testing</a></li>
<li class="chapter" data-level="16.9.2" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#contingency-table-preparation-and-testing"><i class="fa fa-check"></i><b>16.9.2</b> contingency table: preparation and testing</a></li>
</ul></li>
<li class="chapter" data-level="16.10" data-path="ch-chi-square-tests.html"><a href="ch-chi-square-tests.html#effect-size-odds-ratio"><i class="fa fa-check"></i><b>16.10</b> Effect size: odds ratio</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html"><i class="fa fa-check"></i><b>17</b> Other nonparametric tests</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#sec:h17introduction"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#paired-observations-single-sample"><i class="fa fa-check"></i><b>17.2</b> Paired observations, single sample</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#sec:signtest"><i class="fa fa-check"></i><b>17.2.1</b> Sign test</a></li>
<li class="chapter" data-level="17.2.2" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#sec:Wilcoxon-signed-rank"><i class="fa fa-check"></i><b>17.2.2</b> Wilcoxon signed-ranks test</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#independent-observations-multiple-samples"><i class="fa fa-check"></i><b>17.3</b> Independent observations, multiple samples</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#median-test"><i class="fa fa-check"></i><b>17.3.1</b> Median test</a></li>
<li class="chapter" data-level="17.3.2" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#sec:wilcoxon-rank-sum"><i class="fa fa-check"></i><b>17.3.2</b> Wilcoxon rank sum test, or Mann-Whitney U test</a></li>
<li class="chapter" data-level="17.3.3" data-path="ch-other-nonpar-tests.html"><a href="ch-other-nonpar-tests.html#kruskall-wallis-h-test"><i class="fa fa-check"></i><b>17.3.3</b> Kruskall-Wallis H test</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="app-randomnumbers.html"><a href="app-randomnumbers.html"><i class="fa fa-check"></i><b>A</b> Random numbers</a></li>
<li class="chapter" data-level="B" data-path="app-criticalZvalues.html"><a href="app-criticalZvalues.html"><i class="fa fa-check"></i><b>B</b> Standard normal probability distribution</a></li>
<li class="chapter" data-level="C" data-path="app-criticaltvalues.html"><a href="app-criticaltvalues.html"><i class="fa fa-check"></i><b>C</b> Critical values for <span class="math inline">\(t\)</span>-distribution</a></li>
<li class="chapter" data-level="D" data-path="app-criticalchi2values.html"><a href="app-criticalchi2values.html"><i class="fa fa-check"></i><b>D</b> Critical values for <span class="math inline">\(\chi^2\)</span>-distribution</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Created with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Methods and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch:correlation-regression" class="section level1" number="11">
<h1><span class="header-section-number">11</span> Correlation and regression</h1>
<div id="introduction-5" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Introduction</h2>
<p>Most empirical research is focused on establishing associations between
variables. In experimental research, this primarily concerns associations
between independent and dependent variables. In the coming section, we will
look in more detail at the distinct ways of establishing whether a “significant”
(meaningful, non-accidental) relation exists between
the independent and dependent variables. In addition, the researcher might be
interested in the associations between several dependent variables,
for example the associations between the judgements of several
raters or judges (see also Chapter <a href="ch-reliability.html#ch:reliability">12</a>).</p>
<p>In quasi-experimental research, the difference between
independent and dependent variables is usually less clear. Several
variables are observed and the researcher is particularly interested
in the associations between the observed
variables. What, for instance, is the association between the scores for reading,
arithmetic, and geography in the CITO study (see
Table <a href="ch-centre-and-dispersion.html#tab:cito">9.1</a>)? In this chapter, we will look in more detail
into the ways of expressing the association in a number:
a correlation coefficient. There are different correlation coefficients depending on
the variable’s levels of measurement, which we will
examine more in this chapter.</p>
<p>It is advisable to always first make a graphic representation of
an association between the variables, in the form of a so-called
<em>scatter plot</em>,
like in Figure <a href="ch-correlation-regression.html#fig:cito-scatter">11.1</a>. Each point in this scatter plot
corresponds with a pupil (or more generally, with a unit from a
sample). The position of each point (pupil) is determined by the observed
values of two variables (here <span class="math inline">\(X\)</span> is the score for the reading test,
<span class="math inline">\(Y\)</span> is the score for the arithmetic test). A scatter plot like this helps us to
interpret a potential correlation, and to inspect whether the observations
indeed satisfy the preconditions for calculating a correlation from the
observations. In any case, look at (a) the presence of a potential correlation,
(b) the form of that correlation (linear, exponential,…),
(c) potential outliers (extreme observations, see §<a href="ch-centre-and-dispersion.html#sec:outliers">9.4.2</a>),
and (d) the distribution of the two variables,
see §<a href="ch-centre-and-dispersion.html#sec:robustefficient">9.7</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:cito-scatter"></span>
<img src="QMS-EN_files/figure-html/cito-scatter-1.png" alt="Scatter plot of the scores of a reading test and an arithmetic test; see text." width="480" />
<p class="caption">
Figure 11.1: Scatter plot of the scores of a reading test and an arithmetic test; see text.
</p>
</div>
<p>This scatter plot shows (a) that there is a relation between the scores
for reading and arithmetic. The relation is (b) approximately linear, i.e.
can be described as a straight line; we will return to this in
§<a href="ch-correlation-regression.html#sec:regression">11.3</a>.
The relation also helps us to explain the dispersion in the two
variables. After all, the dispersion in the arithmetic scores can
be partially understood or explained from the dispersion in the reading test:
pupils who achieve a relatively good score in reading, also achieve this
in arithmetic. The observations from the two variables thus not
only provide information about the two variables themselves, but moreover
about the association between the variables. In this scatter plot, we can moreover
see (c) that the highest reading score is an outlier (see also Chapter 9,
Figure <a href="ch-centre-and-dispersion.html#fig:cito-boxplot">9.3</a>);
such outliers can have a disproportionately
large influence on the correlation found.</p>
</div>
<div id="sec:Pearson" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Pearson product-moment correlation</h2>
<p>The Pearson product-moment correlation coefficient is referred to with
the symbol <span class="math inline">\(r\)</span> (in the case of two variables). This coefficient can be
used if both variables are observed on the interval level of measurement
(§<a href="ch-levelsofmeasurement.html#sec:interval">4.4</a>), and if both variables are approximately
normally distributed
(§<a href="ch-probability-distributions.html#sec:normaldistribution">10.3</a>). Nowadays, we do this calculation
by computer.</p>
<p>For the observations in the scatter plot in
Fig.<a href="ch-correlation-regression.html#fig:cito-scatter">11.1</a>, we can find a correlation of <span class="math inline">\(r=+.79\)</span>. The
correlation coefficient is a number that is by definition between <span class="math inline">\(-1\)</span>
and <span class="math inline">\(+1\)</span>. A positive correlation coefficient indicates a positive relation:
a larger value of <span class="math inline">\(X\)</span> corresponds with a larger value
of <span class="math inline">\(Y\)</span>. A negative correlation indicates a negative relation:
a larger value of <span class="math inline">\(X\)</span> corresponds with a smaller value of
<span class="math inline">\(Y\)</span>. A value of <span class="math inline">\(r\)</span> which is close to zero indicates a weak
or absent correlation: the dispersion in <span class="math inline">\(X\)</span> is not related to the
dispersion in <span class="math inline">\(Y\)</span>; there is no or only a weak correlation. We call a correlation of
<span class="math inline">\(.4&lt;r&lt;.6\)</span> (or <span class="math inline">\(-.6 &lt; r &lt; -.4\)</span>) moderate. A correlation of
<span class="math inline">\(r&gt;.6\)</span> (or <span class="math inline">\(r&lt; -.6\)</span>) indicates a strong association. If <span class="math inline">\(r=1\)</span> (or
<span class="math inline">\(r=-1\)</span>), then all observations are precisely on a straight line.
Figure <a href="ch-correlation-regression.html#fig:cor-scatter">11.2</a> shows several scatter plots with the
accompanying correlation coefficients.</p>
<div class="figure" style="text-align: center"><span id="fig:cor-scatter"></span>
<img src="QMS-EN_files/figure-html/cor-scatter-1.png" alt="Some scatter plots of observations with accompanying correlation coefficients." width="672" />
<p class="caption">
Figure 11.2: Some scatter plots of observations with accompanying correlation coefficients.
</p>
</div>
<p>The correlation we see between the scores of the two variables (like
<span class="math inline">\(r=.79\)</span> between scores for the reading test and arithmetic test,
Fig.<a href="ch-correlation-regression.html#fig:cito-scatter">11.1</a>) might also be the result of
chance variations in the observations. After all, it is possible that
the pupils who have a good score on the reading test achieve
a good score on the arithmetic test purely by chance — also when there is
actually <em>not</em> a correlation between the two variables in the population. We
refer to the unknown correlation in the population with the Greek letter
<span class="math inline">\(\rho\)</span> (“rho”); as such, it is also possible that <span class="math inline">\(\rho=0\)</span>. Even if <span class="math inline">\(\rho=0\)</span>,
it is possible to have <span class="math inline">\(n=10\)</span> pupils in the sample who <em>by chance</em> combine
high scores on one part with high scores on the other part (and by chance not
have pupils in the sample who combine high scores on one part with low scores
on the other part). We can estimate what the probability <span class="math inline">\(p\)</span> is
of finding this correlation of <span class="math inline">\(r=0.79\)</span> or stronger in a sample of
<span class="math inline">\(n=10\)</span> students, if the association in the population is actually
nil (i.e. if <span class="math inline">\(\rho=0\)</span>). We call this probability <span class="math inline">\(p\)</span> the
<em>significance</em> of the correlation coefficient; in Chapter <a href="ch-testing.html#ch:testing">13</a>,
we will look in more detail at this term ‘significance’.
In anticipation of this: if this probability <span class="math inline">\(p\)</span> is smaller than
<span class="math inline">\(.05\)</span>, then we assume that the correlation found <span class="math inline">\(r\)</span> is <em>not by chance</em>,
i.e. is <em>significant</em>. We often see a small probability <span class="math inline">\(p\)</span> with a strong
correlation <span class="math inline">\(r\)</span>. The correlation coefficient <span class="math inline">\(r\)</span> indicates the direction
and strength of the relation, and the significance <span class="math inline">\(p\)</span> indicates the probability
of finding this relation by chance if <span class="math inline">\(\rho=0\)</span> in the population. We report
these findings as follows<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a>:</p>
<hr />
<blockquote>
<p><em>Example 11.1:</em>
The scores of the <span class="math inline">\(n=10\)</span> pupils on the CITO test subparts in
Table <a href="ch-centre-and-dispersion.html#tab:cito">9.1</a> show a strong correlation between the scores
on the Reading and Arithmetic tests: Pearson <span class="math inline">\(r=0.79, p=.007\)</span>. Pupils
with a relatively high score on one test generally also achieve
a relatively high score on the other test.</p>
</blockquote>
<hr />
<p>In many studies, we are interested in the correlations between more
than two variables. These correlations between variables are often
reported in a so-called pairwise
correlation matrix like
Table <a href="ch-correlation-regression.html#tab:cito-correlations">11.1</a>, which is a table where the correlations
of all pairs of correlations are reported.</p>
<table>
<caption><span id="tab:cito-correlations">Table 11.1: </span> Correlations between the three parts of the CITO
test, as summarised in Table <a href="ch-centre-and-dispersion.html#tab:cito">9.1</a>, with the accompanying significance level between brackets.</caption>
<thead>
<tr class="header">
<th></th>
<th align="center">Reading</th>
<th align="center">Arithmetic</th>
<th align="center">Geography</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reading</td>
<td align="center">1.00</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="even">
<td>Arithmetic</td>
<td align="center">0.79 (.007)</td>
<td align="center">1.00</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Geography</td>
<td align="center">-0.51 (.131)</td>
<td align="center">-0.01 (.970)</td>
<td align="center">1.00</td>
</tr>
</tbody>
</table>
<p>In this matrix, only the lowest (left) half of the complete
matrix is shown. This also suffices because the cells are mirrored
along the diagonal: after all, the correlation between Reading (column 1) and Arithmetic
(row 2) is the same as the correlation between Arithmetic (row 2) and
Reading (row 1). In the cells on the diagonal, the pairwise correlation matrix
always contains the value <span class="math inline">\(1.00\)</span>, since a variable always correlates perfectly with
itself.
We report these findings as follows:</p>
<hr />
<blockquote>
<p><em>Example 11.2:</em> The
pairwise correlations between scores from the <span class="math inline">\(n=10\)</span> pupils on the
three subparts of the CITO test are summarised in
Table <a href="ch-correlation-regression.html#tab:cito-correlations">11.1</a>. We can see a strong correlation between
the scores for the Reading and Arithmetic tests: pupils with a relatively
high score on the Reading test generally also achieve a relatively high
score on the Arithmetic test. The remaining correlations were
not significant.</p>
</blockquote>
<hr />
<div id="formulas-3" class="section level3" number="11.2.1">
<h3><span class="header-section-number">11.2.1</span> Formulas</h3>
<p>The simplest formula for the Pearson product-moment correlation coefficient
<span class="math inline">\(r\)</span> makes use of the standard normal scores we already used earlier
(§<a href="ch-centre-and-dispersion.html#sec:standardscores">9.8</a>):
<span class="math display" id="eq:pearson">\[\begin{equation}
    r_{XY} = \frac{\sum z_X z_Y}{n-1}
  \tag{11.1}
\end{equation}\]</span></p>
<p>Just like when we calculate variance
(formula <a href="ch-centre-and-dispersion.html#eq:variance">(9.3)</a>), we divide again by
<span class="math inline">\((n-1)\)</span> to make an estimate of the association in the population.</p>
</div>
<div id="spss-5" class="section level3" number="11.2.2">
<h3><span class="header-section-number">11.2.2</span> SPSS</h3>
<p>For Pearson’s product-moment correlation coefficient:</p>
<pre><code>Analyze &gt; Correlate &gt; Bivariate...</code></pre>
<p>Choose <code>Pearsons</code> correlation coefficient, tick:
<code>Flag significant correlations</code>. Confirm <code>OK</code>. The resulting
output (table) does not satisfy the style requirements; as such, you should
take the data into or convert it into a table of your own which does satisfy these requirements.</p>
</div>
<div id="jasp-6" class="section level3" number="11.2.3">
<h3><span class="header-section-number">11.2.3</span> JASP</h3>
<p>For Pearson’s product-moment correlation coefficient, go to the top menu bar and choose:</p>
<pre><code>Regression &gt; Classical: Correlation</code></pre>
<p>In the field “Variables”, select the variables of which you want to know the correlation.
Make sure that under “Sample Correlation Coefficient”, option <code>Pearson's r</code> is checked.
Under “Additional Options”, check <code>Report significance</code>, <code>Flag significant correlations</code> and <code>Sample size</code>. You may also check the option <code>Display pairwise</code> to obtain simple table output.
Note that with or without this option checked, the output table does not adhere to APA guidelines for reporting such tables; hence you’ll need to revise the table or create your own using the JASP output.</p>
</div>
<div id="r-6" class="section level3" number="11.2.4">
<h3><span class="header-section-number">11.2.4</span> R</h3>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="ch-correlation-regression.html#cb65-1" aria-hidden="true"></a>cito &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="dt">file=</span><span class="st">&quot;data/cito.txt&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>)</span>
<span id="cb65-2"><a href="ch-correlation-regression.html#cb65-2" aria-hidden="true"></a><span class="co"># variable names are Lezen=Reading, Rekenen=Arithmetic, WO=Geography, ...</span></span>
<span id="cb65-3"><a href="ch-correlation-regression.html#cb65-3" aria-hidden="true"></a><span class="kw">dimnames</span>(cito)[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="kw">c</span>( <span class="st">&quot;Pupil&quot;</span>, <span class="st">&quot;Reading&quot;</span>, <span class="st">&quot;Arithmetic&quot;</span>, <span class="st">&quot;Geography&quot;</span>,</span>
<span id="cb65-4"><a href="ch-correlation-regression.html#cb65-4" aria-hidden="true"></a>                          <span class="st">&quot;UrbanRural&quot;</span>, <span class="st">&quot;Arith.2cat&quot;</span> )</span>
<span id="cb65-5"><a href="ch-correlation-regression.html#cb65-5" aria-hidden="true"></a><span class="kw">cor</span>( cito[,<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>] ) <span class="co"># correlation matrix of columns 2,3,4</span></span></code></pre></div>
<pre><code>##               Reading Arithmetic   Geography
## Reading     1.0000000 0.74921033 -0.50881738
## Arithmetic  0.7492103 1.00000000  0.06351024
## Geography  -0.5088174 0.06351024  1.00000000</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="ch-correlation-regression.html#cb67-1" aria-hidden="true"></a><span class="kw">with</span>( cito, <span class="kw">cor.test</span>( Reading, Arithmetic ) )</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Reading and Arithmetic
## t = 3.1994, df = 8, p-value = 0.01262
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2263659 0.9368863
## sample estimates:
##       cor 
## 0.7492103</code></pre>
</div>
</div>
<div id="sec:regression" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Regression</h2>
<p>The simplest relation that we can distinguish and describe is a linear
relation, i.e. a straight line in the scatter plot
(see Fig.<a href="ch-correlation-regression.html#fig:cor-scatter">11.2</a>). This straight line indicates which value
of <span class="math inline">\(Y_i\)</span> is predicted, on the basis of the value of <span class="math inline">\(X_i\)</span>. This predicted value of
<span class="math inline">\(Y_i\)</span> is noted as <span class="math inline">\(\widehat{Y_i}\)</span>
(“Y-hat”). The best prediction <span class="math inline">\(\widehat{Y_i}\)</span> is based on both the value
of <span class="math inline">\(X_i\)</span> and the linear relation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>:
<span class="math display" id="eq:linearmodel2">\[\begin{equation}
    \widehat{Y_i} = a + b {X_i} 
  \tag{11.2}
\end{equation}\]</span><br />
The straight line is described with
two parameters, namely the intercept (or constant) <span class="math inline">\(a\)</span> and the slope <span class="math inline">\(b\)</span>.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a> The straight line which describes the linear relation is often
referred to as the “regression line”;
after all, we try to trace the observed values of <span class="math inline">\(Y\)</span> back to this linear
function of the values of <span class="math inline">\(X\)</span>.</p>
<p>The difference between the observed value <span class="math inline">\(Y\)</span> and the predicted value
<span class="math inline">\(\widehat{Y}\)</span> <span class="math inline">\((Y-\widehat{Y})\)</span> is called the <em>residual</em> (symbol
<span class="math inline">\(e\)</span>). In other words, the observed value is considered to be
the sum of two components, namely the predicted value and the residual:
<!-- https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations -->
<span class="math display" id="eq:linearmodel3">\[\begin{align}
    Y   &amp;= \widehat{Y} + e \\
        &amp;= a + b X + e 
  \tag{11.3}
\end{align}\]</span></p>
<p>The above rationale is illustrated in the scatter plot in
Figure <a href="ch-correlation-regression.html#fig:cito-linearmodel">11.3</a>. The dashed line indicates the linear relation
between the two tests:
<span class="math display" id="eq:cito-linearmodel">\[\begin{equation}
    \widehat{\textrm{Arithmetic}} = 12.97 + 0.52 \times \textrm{Reading}
  \tag{11.4}
\end{equation}\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:cito-linearmodel"></span>
<img src="QMS-EN_files/figure-html/cito-linearmodel-1.png" alt="Scatter plot of the scores of a reading test and an arithmetic test. The diagram also indicates the regression line (dashed line), the predicted value (green) and residual (red) of the arithmetic test for pupil 2, the average (plus symbol), and markings for pupil 2 and 3; see text." width="480" />
<p class="caption">
Figure 11.3: Scatter plot of the scores of a reading test and an arithmetic test. The diagram also indicates the regression line (dashed line), the predicted value (green) and residual (red) of the arithmetic test for pupil 2, the average (plus symbol), and markings for pupil 2 and 3; see text.
</p>
</div>
<p>This dashed line thus indicates what the value <span class="math inline">\(\widehat{Y}\)</span> is for
each value of <span class="math inline">\(X\)</span>. For the second pupil with <span class="math inline">\(X_2 = 32\)</span>,
we thus predict <span class="math inline">\(\widehat{Y_2} = 12.97 + (0.52) (32) = 29.61\)</span>
(predicted value, green line fragment). For all observations which are not
precisely on the regression line (dashed line),
there is a deviation between the predicted
score <span class="math inline">\(\widehat{Y}\)</span> and the observed score <span class="math inline">\(Y\)</span> (residual, red line
fragment). For the second pupil, this deviation is
<span class="math inline">\(e_2 = (Y_2 - \widehat{Y_2}) = (36-29.61) = 6.49\)</span> (residual, red
line fragment).</p>
<p>As stated, the observed values of <span class="math inline">\(Y\)</span> are considered to be the
sum of two components, the predicted value <span class="math inline">\(\widehat{Y}\)</span>
(green) and the residual <span class="math inline">\(e\)</span> (red). In the same way, the total <em>variance</em>
of <span class="math inline">\(Y\)</span> can be considered to be the sum of the two <em>variances</em> of these
components:
<span class="math display" id="eq:variance-pred-res">\[\begin{equation}
    s^2_{Y} = s^2_{\widehat{Y}} + s^2_e
  \tag{11.5}
\end{equation}\]</span>
Of the total variance
<span class="math inline">\(s^2_Y\)</span> of Y, one part (<span class="math inline">\(s^2_{\widehat{Y}}\)</span>) can be traced back to and/or
explained from the variance of <span class="math inline">\(X\)</span>, via the linear relation described
with parameters <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> (see
formula <a href="ch-correlation-regression.html#eq:linearmodel2">(11.2)</a>), and the other part (<span class="math inline">\(s^2_e\)</span>) cannot be retraced
or explained. The second part, the non-predicted variance of the residuals is also called
the residual variance or unexplained variance.</p>
<p>When we are able to make a good prediction <span class="math inline">\(Y\)</span> from <span class="math inline">\(X\)</span>, i.e. when the Pearson
product-moment correlation coefficient <span class="math inline">\(r\)</span> is high
(Fig. <a href="ch-correlation-regression.html#fig:cor-scatter">11.2</a>, left), then the residuals <span class="math inline">\(e\)</span> are thus relatively
small, the observations are close around the regression line in the scatter
plot, and then the residual variance <span class="math inline">\(s^2_e\)</span> is also relatively small.
Conversely, when we are <em>not</em> able to predict <span class="math inline">\(Y\)</span> well from <span class="math inline">\(X\)</span>, i.e.
when the correlation coefficient is relatively low (Fig. <a href="ch-correlation-regression.html#fig:cor-scatter">11.2</a>, right),
then the residuals <span class="math inline">\(e\)</span> are thus relatively large, the observations are widely dispersed
around the regression line in the scatter plot, and then the residual variance <span class="math inline">\(s^2_e\)</span> is thus
also relatively large. The square of the Pearson
product-moment correlation coefficient <span class="math inline">\(r\)</span> indicates what the relative size of the
two variance components is, with respect to the total
variance:
<span class="math display" id="eq:r2">\[\begin{align}
    r^2 &amp; = \frac{s^2_{\widehat{Y}}}{s^2_Y} \\
        &amp; = 1 - \frac{s^2_e}{s^2_Y}
  \tag{11.6}
\end{align}\]</span>
This statistic <span class="math inline">\(r^2\)</span> is referred to as the “proportion of explained
variance” or as the “coefficient of determination”.</p>
<p>The values of the linear parameters <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> in
formula <a href="ch-correlation-regression.html#eq:linearmodel2">(11.2)</a> are so chosen that the collective
residuals are as small as possible, i.e. that the residual variance
<span class="math inline">\(s^2_e\)</span> is as small as possible (“least squares fit”), and thus <span class="math inline">\(r^2\)</span>
is as large as possible (see
§<a href="ch-correlation-regression.html#sec:regression-formulas">11.3.1</a>). In this way, we can find a straight line
which best fits the observations for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>A linear regression can also be reported as follows:</p>
<hr />
<blockquote>
<p><em>Example 11.3:</em>
Based on a linear regression analysis, it appears that the score
for Arithmetic is related to that for Reading: <span class="math inline">\(b=0.51, r=.79, p_r=.007\)</span>, over <span class="math inline">\(n=10\)</span>
pupils. This linear regression model explains <span class="math inline">\(r^2=.51\)</span> of the
total variance in the arithmetic scores (the residual standard deviation is
<span class="math inline">\(s_e= \sqrt{82.803/(n-1-1)} = 3.217\)</span>).</p>
</blockquote>
<hr />
<div id="sec:regression-formulas" class="section level3" number="11.3.1">
<h3><span class="header-section-number">11.3.1</span> Formulas</h3>
<p>For linear regression of <span class="math inline">\(y\)</span> on <span class="math inline">\(x\)</span>, we try to estimate the coefficients <span class="math inline">\(a\)</span>
and <span class="math inline">\(b\)</span> such that (the square of) the deviation between the predicted value <span class="math inline">\(\hat{y}\)</span>
and the observed value <span class="math inline">\(y\)</span> is as small as possible, in other words that the
square of the residuals <span class="math inline">\((y-\hat{y})\)</span> is as small as possible. This is called the
“least squares” method (see
<a href="http://www.itl.nist.gov/div898/handbook/pmd/section4/pmd431.htm" class="uri">http://www.itl.nist.gov/div898/handbook/pmd/section4/pmd431.htm</a>).</p>
<p>The best estimation for <span class="math inline">\(b\)</span> is
<span class="math display">\[b = \frac{ \sum_{i=1}^n (x_i-\overline{x})(y_i-\overline{y}) } { \sum_{i=1}^n (x_i-\overline{x})^2 }\]</span></p>
<p>The best estimation for <span class="math inline">\(a\)</span> is <span class="math display">\[a = \overline{y} - b \overline{x}\]</span></p>
</div>
<div id="spss-6" class="section level3" number="11.3.2">
<h3><span class="header-section-number">11.3.2</span> SPSS</h3>
<p>For linear regression:</p>
<pre class="console"><code>Analyze &gt; Regression &gt; Linear...</code></pre>
<p>Choose <code>Dependent variable: Arithmetic</code> and choose
<code>Independent variable: Reading</code>. Under the button <code>Statistics</code>, tick
<code>Model fit</code>, tick <code>R squared change</code>, choose <code>Estimates</code>, and afterwards
<code>Continue</code>.<br />
Under the button <code>Plot</code>, tick <code>Histogram</code> and tick also
<code>Normal probability plot</code>; these options are required to a get a
numerical (!) summary over the residuals. 
(already check once)
Under the button <code>Options</code>, choose <code>Include constant</code> to also have
the constant coefficient <span class="math inline">\(a\)</span> calculated. Confirm all choices with <code>OK</code>.</p>
<p>The resulting output includes several tables and figures; you cannot
transfer these directly into your report. The table titled <em>Model
Summary</em> contains the correlation coefficient, indicated here with capital
letter <span class="math inline">\(R=.749\)</span>.<br />
The table titled <em>Coefficients</em> contains the regression coefficients. The
line which has the designation <code>(Constant)</code> states coefficient <span class="math inline">\(a=13.25\)</span>;
the line titled <code>Reading</code> states coefficient <span class="math inline">\(b=0.51\)</span>.<br />
The table titled <em>Residual Statistics</em> provides information about both
the predicted values and the residuals. Check whether the mean of the residual
is indeed null. In this table, we can also see (line 2, column 4) that
the standard variation of the residuals is <span class="math inline">\(3.212\)</span>.</p>
</div>
<div id="jasp-7" class="section level3" number="11.3.3">
<h3><span class="header-section-number">11.3.3</span> JASP</h3>
<p>For linear regression, go to the top menu bar and choose:</p>
<pre><code>Regression &gt; Classical: Linear Regression</code></pre>
<p>Choose the variable <em>Arithmetic</em> as “Dependent Variable”, and choose the variable <em>Reading</em> under “Covariates”.<br />
Next, open the menu bar <code>Model</code>, and inspect whether the predictor <em>Reading</em> is indeed listed under “Model Terms”. The option <code>Include intercept</code> should be checked, in order to have the constant term or intercept <code>a</code> included in the regression model (see §<a href="ch-correlation-regression.html#sec:regression-formulas">11.3.1</a>).<br />
Open the menu bar <code>Statistics</code>, and check the options <code>Estimates</code>, <code>Model fit</code> and <code>R squared change</code>.
Under “Residuals”, check <code>Statistics</code> to obtain a numerical summary of the residuals.
Open the menu bar <code>Plots</code>, and choose plots for <code>Residuals vs. histogram</code> and <code>Q-Q plot standardized residuals</code>; these allow visual inspection of the (distribution of) residuals.</p>
<p>The resulting output contains several tables and figure, which do not conform to APA guidelines and hence cannot be used directly in your report (see also Example 11.3 above).<br />
The table titled <strong>Model Summary</strong> reports the correlation coefficient, here reported with capital <span class="math inline">\(R=.749\)</span>.<br />
The table titled <strong>Coefficients</strong> contains the regression coefficients. The row with indication <code>(Intercept)</code> reports the constant <span class="math inline">\(a=13.25\)</span>; the row with indication <code>Reading</code> reports the slope or regression coefficient <span class="math inline">\(b=0.51\)</span>.<br />
The table titled <strong>Residual Statistics</strong> provides information about the predicted values and residuals. Inspect whether the mean of the residuals is approximately zero (it should be). We also see here (row 2, column 4) that the standard deviation of the residuals is <span class="math inline">\(3.212\)</span>.</p>
</div>
<div id="r-7" class="section level3" number="11.3.4">
<h3><span class="header-section-number">11.3.4</span> R</h3>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="ch-correlation-regression.html#cb71-1" aria-hidden="true"></a><span class="kw">summary</span>( m1 &lt;-<span class="st"> </span><span class="kw">lm</span>( Arithmetic<span class="op">~</span>Reading, <span class="dt">data=</span>cito ) )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Arithmetic ~ Reading, data = cito)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5332 -1.1167 -0.5332  1.7168  6.3384 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  13.2507     4.4910   2.950   0.0184 *
## Reading       0.5128     0.1603   3.199   0.0126 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.406 on 8 degrees of freedom
## Multiple R-squared:  0.5613, Adjusted R-squared:  0.5065 
## F-statistic: 10.24 on 1 and 8 DF,  p-value: 0.01262</code></pre>
<p>The command <code>lm</code> specifies a linear regression model, with <code>Arithmetic</code>
as the dependent variable and <code>Reading</code> as the predictor. This model is
saved as an object called <code>m1</code>, and that is used again directly as an argument
(input) for reporting. In the reporting of model <code>m1</code> the constant coefficient
<span class="math inline">\(a\)</span> is referred to as the <code>Intercept</code>.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="ch-correlation-regression.html#cb73-1" aria-hidden="true"></a><span class="kw">sd</span>( <span class="kw">resid</span>( m1 ) ) <span class="co"># s.d. of residuals according to `m1`</span></span></code></pre></div>
<pre><code>## [1] 3.211533</code></pre>
</div>
</div>
<div id="influential-observations" class="section level2" number="11.4">
<h2><span class="header-section-number">11.4</span> Influential observations</h2>
<p>In the previous section, we saw that the aim in a correlation analysis
or regression analysis is for a minimal residual variance.
Earlier we also already saw that outliers or extreme observations, by definition,
make a relatively large contribution to variance. Together, this means that
outliers or extreme observations can have a large influence on the size of
the correlation or on the regression found (the linear relation found). Pupil 3 has an
extremely high score for Reading (see also
Fig.<a href="ch-centre-and-dispersion.html#fig:cito-boxplot">9.3</a>). If we discount pupil 3, then this would not greatly
change the correlation (<span class="math inline">\(r_{-3}=.79\)</span>) but it would change the slope of the regression line
(<span class="math inline">\(b=0.84\)</span>, more than one and a half times as large as if pupil 3 were in fact included).
This observation thus “pulls” hard on the regression line, precisely because
this observation has an extreme value for <span class="math inline">\(X\)</span> and therefore has much influence.</p>
<p>Non-extreme observations can, however, also have a large influence on the
correlation and regression, if they are far away from the regression line
and thus make a large contribution to the residual variance. This too can be seen in
Fig.<a href="ch-correlation-regression.html#fig:cito-linearmodel">11.3</a>.
Pupil 2 has no extreme scores
but does have the largest residual. If we discounted this pupil 2 then the
correlation would be considerably higher
(<span class="math inline">\(r_{-2}=.86\)</span>) but the slope of the regression line would only
change a little (<span class="math inline">\(b=0.45\)</span>).</p>
<p>For a correlation analysis or regression analysis you always have
to make and study a scatter plot, in order to see the pattern for yourself (is it linear?) and to inspect whether and to what extent the results
may have been influenced by one or a few observation(s). Pay
particular attention to observations which are far away from the mean, for each
of the two variables, and to observations which are far away from the regression line.</p>
</div>
<div id="sec:Spearman" class="section level2" number="11.5">
<h2><span class="header-section-number">11.5</span> Spearman’s rank correlation coefficient</h2>
<p>The variables whose correlation we want to investigate
are not always both expressed on the interval level of measurement
(§<a href="ch-levelsofmeasurement.html#sec:interval">4.4</a>), regardless whether or not the researchers
want to and are able to assume that both variables are
approximately normally distributed
(§<a href="ch-probability-distributions.html#sec:normaldistribution">10.3</a>).
In that case, the product-moment correlation is less suitable for
quantifying the association. If the data is indeed expressed on an
ordinal level of measurement, then we can use other correlation coefficients
to express the association: Spearman’s rank correlation coefficient
(<span class="math inline">\(r_s\)</span>) and Kendall’s <span class="math inline">\(\tau\)</span> (the Greek letter “tau”). Both of these coefficients
are based on the ranking of the observations; we can thus always compute these correlations
when we are able to order the observations. Nowadays, we also perform this calculation
by computer. In this chapter, we only discuss the Spearman’s rank correlation
coefficient.</p>
<p>The Spearman’s rank correlation coefficient is equal to the Pearson
product-moment correlation coefficient applied to the ranks of
the observations. We convert every observation from a variable to
a rank number, from the smallest observed value (rank 1)
to the largest observed value (rank <span class="math inline">\(n\)</span>). If two or more observations
have the same value, then they also receive the same
(mean) rank. In
Table <a href="ch-correlation-regression.html#tab:cito-ranks">11.2</a>, you can see the ranks of the scores for Reading
and Arithmetic, ordered here according to the ranks for Reading.</p>
<table>
<caption><span id="tab:cito-ranks">Table 11.2: </span> Ranks for the scores of 10 pupils on parts of a test, as summarised in
Table <a href="ch-centre-and-dispersion.html#tab:cito">9.1</a>, with difference <span class="math inline">\(v_i\)</span> between the two ranks per pupil.</caption>
<thead>
<tr class="header">
<th align="left">Pupil</th>
<th align="center">1</th>
<th align="center">9</th>
<th align="right">6</th>
<th align="center">4</th>
<th align="center">10</th>
<th align="right">8</th>
<th align="center">5</th>
<th align="center">7</th>
<th align="center">2</th>
<th align="center">3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Reading</td>
<td align="center">1</td>
<td align="center">2</td>
<td align="right">3</td>
<td align="center">4.5</td>
<td align="center">4.5</td>
<td align="right">6</td>
<td align="center">7</td>
<td align="center">8</td>
<td align="center">9</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="left">Arithmetic</td>
<td align="center">2</td>
<td align="center">4</td>
<td align="right">1</td>
<td align="center">4</td>
<td align="center">6.5</td>
<td align="right">4</td>
<td align="center">8</td>
<td align="center">6.5</td>
<td align="center">10</td>
<td align="center">9</td>
</tr>
<tr class="odd">
<td align="left">Difference <span class="math inline">\(v_i\)</span></td>
<td align="center">-1</td>
<td align="center">-2</td>
<td align="right">1</td>
<td align="center">0.5</td>
<td align="center">-2</td>
<td align="right">2</td>
<td align="center">-1</td>
<td align="center">1.5</td>
<td align="center">-1</td>
<td align="center">1</td>
</tr>
</tbody>
</table>
<p>The ranking in Table <a href="ch-correlation-regression.html#tab:cito-ranks">11.2</a> makes it clear at a glance that
the three pupils with the lowest score for Reading (nos. 1, 9, 6) also almost achieved
the lowest scores for Arithmetic. That indicates a positive
relation. The two best readers (nos. 2 and 3) are also the two best
arithmeticians. That also indicates a positive relation. However, there is
also no question of a perfect positive relation (thus here <span class="math inline">\(r_s&lt;1\)</span>), because
then the two rankings would match perfectly.</p>
<p>Think how Table <a href="ch-correlation-regression.html#tab:cito-ranks">11.2</a> would look if there were a perfect
negative relation (<span class="math inline">\(r_s=-1\)</span>) between the scores for Reading and
Arithmetic, and how the table would look if there were no correlation whatsoever
(<span class="math inline">\(r_s=0\)</span>) between these scores.</p>
<div id="formulas-4" class="section level3" number="11.5.1">
<h3><span class="header-section-number">11.5.1</span> Formulas</h3>
<p>The association between the rankings of the two variables is expressed
in the Spearman’s rank correlation coefficient:
<span class="math display" id="eq:spearman">\[\begin{equation}
    r_s = 1 - \frac{6 \sum v_i^2}{n(n^2-1)}
  \tag{11.7}
\end{equation}\]</span>
in which <span class="math inline">\(v_i\)</span> stands for
the difference in rankings on both variables for respondent <span class="math inline">\(i\)</span>. The fraction
in this formula gets larger and <span class="math inline">\(r_s\)</span> thus gets smaller, the larger the
differences between the ranks are.
However, this formula can only be used if there are no “ties” (shared rankings) in the
variables; for the dataset in Table <a href="ch-correlation-regression.html#tab:cito-ranks">11.2</a> with “ties” in both variables
we have to use another formula.</p>
<p>As can be seen, the Spearman’s rank correlation <span class="math inline">\(r_s\)</span> is not equal to the
Pearson product-moment correlation <span class="math inline">\(r\)</span> for the scores observed.
If the preconditions of the Pearson coefficient are satisfied, then this
Pearson product-moment correlation coefficient provides a better estimation of the
association than the Spearman’s rank correlation coefficient. However, if the preconditions
are <em>not</em> satisfied, then the Spearman’s coefficient should be preferred again. The
Spearman’s coefficient is, amongst others, less sensitive for influential extreme
observations — after all, such outliers have less weighting once the
raw scores have been replaced by the ranks.</p>
</div>
<div id="spss-7" class="section level3" number="11.5.2">
<h3><span class="header-section-number">11.5.2</span> SPSS</h3>
<p>For Spearman’s rank correlation coefficient:</p>
<pre><code>Analyze &gt; Correlate &gt; Bivariate...</code></pre>
<p>Choose <code>Spearman</code> rank correlation coefficient, tick:
<code>Flag significant correlations</code>. Confirm with <code>OK</code>. The resulting
output (table) does not satisfy the style requirements; you thus have to take
the data into or convert it into a table of your own which does satisfy these requirements,
and report according to the usual conventions for correlation analysis.</p>
</div>
<div id="jasp-8" class="section level3" number="11.5.3">
<h3><span class="header-section-number">11.5.3</span> JASP</h3>
<p>For Spearman’s rank correlation coefficient, go to the top menu bar and choose:</p>
<pre><code>Regression &gt; Classical: Correlation</code></pre>
<p>In the field “Variables”, select the variables of which you want to know the correlation.
Make sure that under “Sample Correlation Coefficient”, option <code>Spearman's rho</code> is checked.
Under “Additional Options”, check <code>Report significance</code>, <code>Flag significant correlations</code> and <code>Sample size</code>. You may also check the option <code>Display pairwise</code> to obtain simple table output.
Note that with or without this option checked, the output table does not adhere to APA guidelines for reporting such tables; hence you’ll need to revise the table or create your own using the JASP output.</p>
</div>
<div id="r-8" class="section level3" number="11.5.4">
<h3><span class="header-section-number">11.5.4</span> R</h3>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="ch-correlation-regression.html#cb77-1" aria-hidden="true"></a><span class="kw">with</span>(cito, <span class="kw">cor.test</span>( Reading,Arithmetic, <span class="dt">method=</span><span class="st">&quot;spearman&quot;</span> ) )</span></code></pre></div>
<pre><code>## Warning in cor.test.default(Reading, Arithmetic, method = &quot;spearman&quot;): Cannot
## compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  Reading and Arithmetic
## S = 25.229, p-value = 0.00198
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.8470988</code></pre>
</div>
</div>
<div id="sec:Phi" class="section level2" number="11.6">
<h2><span class="header-section-number">11.6</span> Phi</h2>
<p>The two variables for which we want to investigate the association are themselves
not always expressed on an ordinal level of measurement (Chapter <a href="ch-levelsofmeasurement.html#ch:levelsofmeasurement">4</a>).
Even if both of the variables are measured only on a nominal level of measurement,
then a correlation can still be calculated, namely the phi correlation coefficient
(symbol <span class="math inline">\(r_\Phi\)</span>, with Greek letter “Phi”). This correlation coefficient can also be used
if one of the two variables is measured on a nominal level of measurement,
and the other one is measured on an ordinal level of measurement.</p>
<p>With our CITO test example, let us assume that the first five
pupils come from a large city (urban), and the last five from the
countryside (rural). The pupil’s place of origin is a nominal variable,
with 2 categories, here randomly referred to as <code>1</code> resp. <code>0</code> (see
§<a href="ch-levelsofmeasurement.html#sec:nominal">4.2</a>; a nominal variable with precisely 2
categories is also called a binomial or dichotomous variable).
We now ask ourselves whether there is some association between a
pupil’s place of origin and their score for the Arithmetic part of the CITO test.
The second variable is of interval level of measurement. We convert this to a
nominal level of measurement. That can be done in many ways, and it is the
researcher’s role to make a wise choice when doing so. Here, we
choose the often used ‘mean split’: one of the categories (low, code <code>0</code>)
consists of scores smaller than or equal to the mean
(§<a href="ch-centre-and-dispersion.html#sec:mean">9.3.1</a>), and the other category consists of scores larger
than the mean (high, code <code>1</code>). We summarise the number of pupils in each of the
<span class="math inline">\(2\times 2\)</span> categories in a contingency table
(Tabel <a href="ch-correlation-regression.html#tab:cito-contingency-table">11.3</a>).</p>
<table>
<caption><span id="tab:cito-contingency-table">Table 11.3: </span> Contingency table of <span class="math inline">\(n=10\)</span> pupils, subdivided according
to origin (urban=1, rural=0) and according to category of score for the Arithmetic part of
the CITO test (‘mean split’, low=0, high=1), with letter designations for the number
of observations; see text.</caption>
<thead>
<tr class="header">
<th align="left">Origin</th>
<th align="center">Low (0)</th>
<th align="center">High (1)</th>
<th align="center">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Rural (0)</td>
<td align="center">5 (A)</td>
<td align="center">0 (B)</td>
<td align="center">5 (A+B)</td>
</tr>
<tr class="even">
<td align="left">Urban (1)</td>
<td align="center">2 (C)</td>
<td align="center">3 (D)</td>
<td align="center">5 (C+D)</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="center">7 (A+C)</td>
<td align="center">3 (B+D)</td>
<td align="center">10 (A+B+C+D)</td>
</tr>
</tbody>
</table>
<p>The nominal correlation coefficient <span class="math inline">\(r_\Phi\)</span> is equal to the Pearson
product-moment correlation coefficient applied to the binomial codes
(<code>0</code> and <code>1</code>) of the observations. All 5 pupils from the rural countryside
have an Arithmetic score which is equal to or lower than average
(<span class="math inline">\(\overline{y}=\)</span> 27.2); out of the pupils from the urban city, 2 have a
score which is (equal to or) lower than average. There is thus an association<br />
between the binomial codes of the rows (origin) and those of the columns
(score categories) in Table <a href="ch-correlation-regression.html#tab:cito-contingency-table">11.3</a>.
This association is quantified in the
correlation coefficient <span class="math inline">\(r_\Phi=0.65\)</span> for this data.</p>
<div id="formulas-5" class="section level3" number="11.6.1">
<h3><span class="header-section-number">11.6.1</span> Formulas</h3>
<p>The nominal correlation coefficient <span class="math inline">\(r_\Phi\)</span> is calculated as follows,
where the letters refer to the numbers in the cells of a contingency table
(see Table <a href="ch-correlation-regression.html#tab:cito-contingency-table">11.3</a>):
<span class="math display" id="eq:phi">\[\begin{equation}
    r_\Phi = \frac{(AD-BC)}{\sqrt{(A+B)(C+D)(A+C)(B+D)}}
  \tag{11.8}
\end{equation}\]</span></p>
<p>For the example discussed above we then find
<span class="math display">\[
    r_\Phi = \frac{(15-0)}{\sqrt{(5)(5)(7)(3)}} = \frac{15}{22.91} = 0.65
\]</span></p>
</div>
<div id="spss-8" class="section level3" number="11.6.2">
<h3><span class="header-section-number">11.6.2</span> SPSS</h3>
<p>The dataset <code>cito</code> already contains the variable <code>UrbanRural</code> which indicates the
origin of the pupils. However, for completeness, we will still show how you can
construct a variable like this for yourself.</p>
<div id="construct-new-variable" class="section level4" number="11.6.2.1">
<h4><span class="header-section-number">11.6.2.1</span> construct new variable</h4>
<pre><code>Transform &gt; Recode into different variables...</code></pre>
<p>Choose <code>Pupil</code> as the old variable and fill in as the new name for the new variable
<code>UrbanRural2</code>. Indicate that the old values in <code>Range</code> from
1 to 5 (old) have to be transformed to the new value 1, and likewise that
pupils 6 to 10 have to get the new value 0 for the new variable
<code>UrbanRural2</code>.</p>
<p>For <code>Arithmetic</code> it is a bit more complex. You firstly have to delete
your transformation rules (which relate to <code>UrbanRural</code>). Then, make a new variable
again in the same way as before, named <code>Arithmetic2</code>.
All values from the lowest value to the mean (<span class="math inline">\(27.2\)</span>) are transformed to the
new value 0 for this new variable. All values
from the mean (<span class="math inline">\(27.2\)</span>) to the highest value are transformed to the new value 1.</p>
</div>
<div id="correlation-analysis" class="section level4" number="11.6.2.2">
<h4><span class="header-section-number">11.6.2.2</span> correlation analysis</h4>
<p>After this preparatory work, we can finally calculate <span class="math inline">\(r_\Phi\)</span>.</p>
<pre><code>Analyze &gt; Descriptives &gt; Crosstabs...</code></pre>
<p>Select the variables <code>UrbanRural2</code> (in the “Rows” panel) and <code>Arithmetic2</code>
(in the “Columns” panel) for
contingency table @ref(tab: cito-contingency-table).<br />
Choose <code>Statistics…</code> and tick the option <code>Phi and Cramer’s V</code>!<br />
Confirm firstly with <code>Continue</code> and then again with <code>OK</code>.</p>
</div>
</div>
<div id="jasp-9" class="section level3" number="11.6.3">
<h3><span class="header-section-number">11.6.3</span> JASP</h3>
<p>The dataset <code>cito</code> already contains a variable <code>UrbanRural</code> which indicates the pupils’ origins.
However, for completeness, let us still see how you can construct such a variable for yourself.</p>
<div id="construct-new-variable-1" class="section level4" number="11.6.3.1">
<h4><span class="header-section-number">11.6.3.1</span> construct new variable</h4>
<p>First, create a new variable by clicking the <strong>+</strong> button which is to the right of the rightmost column header in the data sheet. A new panel “Create Computed Column” will appear, in which you can enter a name for the new variable, such as <code>UrbanRural2</code>.
There are two methods to specify the new variable, using <code>R</code> commands or using a hand pointer sign (manual specification). Below we will explain for both options how to specify the new variable. You can also indicate the measurement level of the new variable; in this example we will use <code>Nominal</code>. Finally, click on <code>Create Column</code> to create the new variable, which will appear as a new empty column in the data sheet.</p>
<p>If you chose the <code>R</code> command method to define a new variable, then a new panel will appear above the data sheet, with the text “#Enter your R code here :)”. You can enter some <code>R</code> commands and use <code>R</code> functions<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a> to define the new variable. Enter your <code>R</code> commands and click on <code>Compute column</code> to fill the empty variable with the new values.</p>
<p>For the new <code>UrbanRural2</code> variable in this example we may use this code:</p>
<pre><code>ifelse(Leerling &lt;= 5, 1, 0) </code></pre>
<p>This command means: <em>if</em> the value of ID variable <code>Leerling</code> (Pupil) is less than or equal to 5 (this if-condition is the first argument), then the new value will be 1 (the second argument), <em>else</em> the new value will be 0 (the third argument). In short: if Leerling <span class="math inline">\(\leq\)</span> 5, then 1, else 0.
Note that this <code>R</code> command will only work in JASP if the variable in the first argument is at the “Scale” level of measurement; otherwise the <code>&lt;=</code> operator is not defined. If the measurement level of the source variable is not set to “Scale”, then you may change this by going to the data sheet, click on the icon that indicates the measurement level, in the column header, and then select “Scale”.</p>
<p>If you chose the manual specification method (hand pointer) to define the new variable, then a new panel will appear above the data sheet. The panel has variables to the left, math symbols at the top, and some functions to the right. Here you can manually build the expression to define the new variable. After you have built your expression (see below), click on <code>Compute column</code> to fill the empty variable with the new values.</p>
<p>For the new <code>UrbanRural2</code> variable in this example, scroll down through the functions on the righthandd side, and click on <code>ifElse(y)</code>. The function appears in the working panel. Replace the arguments “test” and “then” and “else” by appropriate values.<br />
– Click on “test” and select the symbol <span class="math inline">\(\leq\)</span> from the top. Drag variable <em>Leerling</em> (Pupil) from the left side to the dots preceding the <span class="math inline">\(\leq\)</span> operator, and enter the value <code>5</code> following the operator.<br />
– For “then” type <code>1</code>.<br />
– For “else” type <code>0</code>.<br />
The complete expression should read <code>ifElse(Leerling &lt;= 5,1,0)</code>, and this expression is equivalent to the <code>R</code> command discussed above.</p>
<p>As explained above for <code>R</code> commands within JASP, the expression built here, containing a <span class="math inline">\(\leq\)</span> or <code>&lt;=</code> operator, will only work in JASP if the variable in the first argument is at the “Scale” level of measurement; otherwise the <code>&lt;=</code> operator is not defined. If the measurement level of the source variable is not set to “Scale”, then you may change this by going to the data sheet, click on the icon that indicates the measurement level, in the column header, and then select “Scale”.</p>
<p>We repeat the same create-and-define steps as above, now for a new version of the variable <em>Arithmetic</em>: the new variable will be named <code>Arithmetic2</code> and it will be at the <code>Nominal</code> level.</p>
<p>First we create a new variable by clicking the <strong>+</strong> button to the right of the rightmost column header in the data sheet. A new panel “Create Computed Column” will appear, in which you can enter a name for the new variable, such as <code>UrbanRural2</code>. Click on <code>Create Column</code> to create the new variable, which will appear as a new empty column in the data sheet.</p>
<p>If you chose the <code>R</code> command method to define this new variable, then you may use this <code>R</code> code:</p>
<pre><code>ifelse(Arithmetic &lt; mean(Arithmetic), 0, 1)</code></pre>
<p>This command means: <em>if</em> the value of the source variable <code>Arithmetic</code> is less than the mean of the same variable <code>Arithmetic</code>, <em>then</em> the new value will be zero (mnemonic code for “low”), and <em>else</em> the new value will be one (code for “high”). In short: if Arithmetic &lt; mean(Arithmetic), then 0, else 1. Enter the <code>R</code> command given above, and click on <code>Compute column</code> to fill the empty variable with the specified (nominal) values.</p>
<p>If you chose the manual specification method (hand pointer) to define the new variable, then you need to select the function <code>ifElse(y)</code> once more. For “test”, select the <span class="math inline">\(&lt;\)</span> operator from the top, drag the function <code>mean(y)</code> from the righthand menu to the preceding dots, and drag the variable <code>Arithmetic</code> from the lefthand menu to the “values” part of the <code>mean(y)</code> function. For “then” enter <code>0</code> and for “else” enter <code>1</code>. The complete expression should read <code>ifElse(Arithmetic &lt; mean(Arithmetic), 0, 1)</code>, and this expression is equivalent to the <code>R</code> command discussed above.
After you have built your expression, click on <code>Compute column</code> to fill the empty variable with the new values.</p>
</div>
<div id="correlation-analysis-1" class="section level4" number="11.6.3.2">
<h4><span class="header-section-number">11.6.3.2</span> correlation analysis</h4>
<p>After all this preparatory work, we can finally calculate <span class="math inline">\(r_\Phi\)</span>. From the top menu bar, choose</p>
<pre><code>Frequencies &gt; Classical: Contingency Tables</code></pre>
<p>Select the variables <code>UrbanRural2</code> (for the “Rows” panel) and <code>Arithmetic2</code> (for the “Columns” panel) to obtain the contingency table (see Table <a href="ch-correlation-regression.html#tab:cito-contingency-table">11.3</a>) .
Open the <code>Statistics</code> menu bar, and under “Nominal” check <code>Phi and Cramer’s V</code>.
The value of <span class="math inline">\(r_\Phi\)</span> is reported in the output under the heading <strong>Phi coefficient</strong>.</p>
</div>
</div>
<div id="r-9" class="section level3" number="11.6.4">
<h3><span class="header-section-number">11.6.4</span> R</h3>
<p>The dataset <code>cito</code> already contains a variable <code>UrbanRural</code> which indicates the pupils’ origins.
However, for completeness, let us still see how you can construct such a variable for yourself.</p>
<div id="construct-new-variable-2" class="section level4" number="11.6.4.1">
<h4><span class="header-section-number">11.6.4.1</span> construct new variable</h4>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="ch-correlation-regression.html#cb85-1" aria-hidden="true"></a>UrbanRural2 &lt;-<span class="st"> </span><span class="kw">ifelse</span>( cito<span class="op">$</span>Pupil<span class="op">&lt;</span><span class="dv">6</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="co"># 1=urban, 0=rural</span></span>
<span id="cb85-2"><a href="ch-correlation-regression.html#cb85-2" aria-hidden="true"></a>Arithmetic2 &lt;-<span class="st"> </span><span class="kw">ifelse</span>( cito<span class="op">$</span>Arithmetic<span class="op">&gt;</span><span class="kw">mean</span>(cito<span class="op">$</span>Arithmetic), <span class="dv">1</span>, <span class="dv">0</span> ) <span class="co"># 1=high, 0=low</span></span></code></pre></div>
<p>Here we build a new variable <code>Arithmetic2</code>, which has the value <code>1</code> if the score for
Arithmetic is higher than the average, and otherwise has the value <code>0</code>.</p>
</div>
<div id="correlation-analysis-2" class="section level4" number="11.6.4.2">
<h4><span class="header-section-number">11.6.4.2</span> correlation analysis</h4>
<p>In R, we also start by making a contingency table (Table <a href="ch-correlation-regression.html#tab:cito-contingency-table">11.3</a>) and we then calculate the <span class="math inline">\(r_\Phi\)</span> over the contingency table.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="ch-correlation-regression.html#cb86-1" aria-hidden="true"></a><span class="kw">print</span>( <span class="kw">table</span>(UrbanRural2,Arithmetic2) -&gt;<span class="st"> </span>citocontingencytable ) </span></code></pre></div>
<pre><code>##            Arithmetic2
## UrbanRural2 0 1
##           0 5 0
##           1 2 3</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="ch-correlation-regression.html#cb88-1" aria-hidden="true"></a><span class="co"># make and store a contingency table</span></span>
<span id="cb88-2"><a href="ch-correlation-regression.html#cb88-2" aria-hidden="true"></a><span class="cf">if</span> (<span class="kw">require</span>(psych)) { <span class="co"># for psych::phi</span></span>
<span id="cb88-3"><a href="ch-correlation-regression.html#cb88-3" aria-hidden="true"></a>  <span class="kw">phi</span>(citocontingencytable) <span class="co"># contingency table made earlier is input here!</span></span>
<span id="cb88-4"><a href="ch-correlation-regression.html#cb88-4" aria-hidden="true"></a>}</span></code></pre></div>
<pre><code>## Loading required package: psych</code></pre>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;.hqenv&#39;:
## 
##     harmonic.mean, logit</code></pre>
<pre><code>## [1] 0.65</code></pre>
</div>
</div>
</div>
<div id="sec:correlationcausation" class="section level2" number="11.7">
<h2><span class="header-section-number">11.7</span> Last but not least</h2>
<p>At the end of this chapter, we want to emphasise again that an association or correlation
between two variables does not necessarily mean
that there is a causal relation between the variables, in other words
a correlation does not mean that one variable (e.g. treatment) is the consequence of
the other variable (e.g. cure).
The common saying for this is “correlation does not imply
causation,” see also Example 6.1 (Chapter <a href="ch-design.html#ch:design">6</a>)
and accompanying Figure <a href="ch-correlation-regression.html#fig:xkcd552">11.4</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:xkcd552"></span>
<img src="figures/correlation.png" alt="_Correlation does not imply causation_, borrowed with permission from &lt;http://xkcd.com/552&gt;."  />
<p class="caption">
Figure 11.4: <em>Correlation does not imply causation</em>, borrowed with permission from <a href="http://xkcd.com/552" class="uri">http://xkcd.com/552</a>.
</p>
</div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="25">
<li id="fn25"><p>When the correlation found <span class="math inline">\(r\)</span> is <em>not</em> significant, then this can thus be by chance,
and then we discount an interpretation of the correlation. We do then state in our report
the correlation coefficient found and the established significance for it.<a href="ch-correlation-regression.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>In some school books, this equation is described as <span class="math inline">\(Y = a X + b\)</span>, with <span class="math inline">\(a\)</span> as the slope and <span class="math inline">\(b\)</span> as the intercept; however, we keep to the conventional international notation here.<a href="ch-correlation-regression.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Only selected <code>R</code> functions from a so-called “whitelist” of functions are allowed.<a href="ch-correlation-regression.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch-probability-distributions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch-reliability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/ch11correlation-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["QMS-EN.pdf", "QMS-EN.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
